### ISSUE TITLE
PIP install pandas==1.0.2 on Python 3.9+ fails to install

### ISSUE THREAD

**Issue by SietsmaRJ** [molgenis/capice#28]
Attempting to run `pip install pandas==1.0.2` in a virtual environment created in python 3.9+ issues the error: ERROR: Command errored out with exit status 1

**Comment by SietsmaRJ** [comment]
The error while installing pandas 1.0.2 can be resolved by simply installing pandas 1.2.3. However: this raises a new error within the python pickle library: 

`Traceback (most recent call last):
  File "capice/test_global.py", line 203, in test_unit_preprocessing
    self.main.preprocess(loaded_cadd_data=imputed_file, train=False)
  File "capice/src/main.py", line 106, in preprocess
    cadd_data = preprocessor.preprocess(datafile=loaded_cadd_data)
  File "capice/src/preprocessors/preprocessor.py", line 106, in preprocess
    processed_data = self.preprocessor.preprocess(dataset=datafile, is_train=self.train)
  File "capice/src/models/model_abstract.py", line 130, in preprocess
    self._load_model()
  File "capice/src/models/model_abstract.py", line 309, in _load_model
    model = pickle.load(model_file)
_pickle.UnpicklingError: NEWOBJ class argument isn't a type object`
