### ISSUE TITLE
[CAPICE2VCF] Updated CAPICE causes a "not a .tsv file" error.

### ISSUE THREAD

**Issue by SietsmaRJ** [molgenis/capice#30]
Running the [updated CAPICE](https://github.com/SietsmaRJ/capice) though the [VIP](https://github.com/molgenis/vip) causes an error in the Capice2VCF as following:

```
java.lang.IllegalArgumentException: Input file '/local/415774/tmp.poywevebbh/2_annotate/2_capice/3_capice_predict/test_vip.vcf.gz.tsv.gz' is not a .tsv file.
	at org.molgenis.capice.AppCommandLineOptions.validateInput(AppCommandLineOptions.java:90)
	at org.molgenis.capice.AppCommandLineOptions.validateCommandLine(AppCommandLineOptions.java:69)
	at org.molgenis.capice.AppCommandLineRunner.createSettings(AppCommandLineRunner.java:104)
	at org.molgenis.capice.AppCommandLineRunner.run(AppCommandLineRunner.java:74)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:795)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:779)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at org.molgenis.capice.App.main(App.java:10)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:109)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)

```

The bug can be replicated by using the new CAPICE, the [easybuild CAPICE/v1.3.0](https://github.com/molgenis/easybuild-easyconfigs/blob/master/easybuild/easyconfigs/c/CAPICE/CAPICE-v1.3.0-foss-2018b.eb) module and trying to convert the output of [new CAPICE](https://github.com/SietsmaRJ/capice) through CAPICE2VCF.

**Comment by dennishendriksen** [comment]
capice2vcf was removed in v2.0.1
