### ISSUE TITLE
[CAPICE2VCF] Updated CAPICE causes a NumberFormatException for input "String"

### ISSUE THREAD

**Issue by SietsmaRJ** [molgenis/capice#31]
Running [updated CAPICE](https://github.com/SietsmaRJ/capice) though CAPICE2VCF, temporary disabling gzipping the output of CAPICE to avoid [Issue #30](https://github.com/molgenis/capice/issues/30), raises the following error:

```
java.lang.IllegalStateException: java.lang.NumberFormatException: For input string: "FRAME_SHIFT"
	at org.molgenis.capice.vcf.TsvToVcfMapperImpl.getPrediction(TsvToVcfMapperImpl.java:104)
	at org.molgenis.capice.vcf.TsvToVcfMapperImpl.mapLine(TsvToVcfMapperImpl.java:66)
	at org.molgenis.capice.vcf.TsvToVcfMapperImpl.mapCapiceOutput(TsvToVcfMapperImpl.java:56)
	at org.molgenis.capice.vcf.TsvToVcfMapperImpl.map(TsvToVcfMapperImpl.java:43)
	at org.molgenis.capice.vcf.CapiceServiceImpl.mapPredictionsToVcf(CapiceServiceImpl.java:36)
	at org.molgenis.capice.AppCommandLineRunner.run(AppCommandLineRunner.java:87)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:795)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:779)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at org.molgenis.capice.App.main(App.java:10)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:109)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: java.lang.NumberFormatException: For input string: "FRAME_SHIFT"
	at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
	at java.base/jdk.internal.math.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
	at java.base/java.lang.Float.parseFloat(Float.java:455)
	at org.molgenis.capice.vcf.TsvToVcfMapperImpl.getPrediction(TsvToVcfMapperImpl.java:101)
	... 19 common frames omitted
```

This is likely, reading the error message, due to changes in the output format of updated CAPICE.

Currently, the output of CAPICE looks like this:
|  chr_pos_ref_alt  |  GeneName  |  Consequence  |  PHRED  |  probabilities  |  prediction  |  combined_prediction  |
| ---- |----| ---- | ---- | ---- | ---- | ---- |
| _string_ |_string_|_string_|_float_|_float_| _string_ |_string_|

New CAPICE output looks like this:

|  chr_pos_ref_alt  |  GeneName  |  FeatureID |  Consequence |  probabilities  |
| ---- |----| ---- | ---- | ---- |
| _string_ |_string_|_string_|_string_|_float_|

**Comment by dennishendriksen** [comment]
capice2vcf was removed in v2.0.1
